// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijjsledpmeizgpfxzpmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqanNsZWRwbWVpemdwZnh6cG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTA4NDYsImV4cCI6MjA2NjU4Njg0Nn0.tltPKxr7VxbFagOnswUa80WZ8qGj852RTIvHyaNQ5XI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);